//SURVEY
export const RESET_SURVEY               = 'RESET_SURVEY';
export const SELECT_GENDER              = 'SELECT_GENDER';
export const SELECT_MENS_COLLECTION     = 'SELECT_MENS_COLLECTION';
export const SELECT_WOMENS_COLLECTION   = 'SELECT_WOMENS_COLLECTION';
export const SELECT_COLOR               = 'SELECT_COLOR';
export const SELECT_SHIRT_TYPE          = 'SELECT_SHIRT_TYPE';
export const SELECT_PANTS_TYPE          = 'SELECT_PANTS_TYPE';
export const SELECT_WOMEN_CLOTHING_TYPE = 'SELECT_WOMEN_CLOTHING_TYPE';

//RECOMMENDATION
export const RESET_RECOMMENDATION = 'RESET_RECOMMENDATION';
export const SET_CURRENT_OUTFIT = 'SET_CURRENT_OUTFIT';
export const GET_SHIRTS         = 'GET_SHIRTS';
export const GET_PANTS          = 'GET_PANTS';
export const GET_ONE_PIECES     = 'GET_ONE_PIECES';
export const GET_OUTERWEAR      = 'GET_OUTERWEAR';
export const GET_SHOES          = 'GET_SHOES';
export const GET_ACCESSORIES    = 'GET_ACCESSORIES';

//ORDER
export const GET_ORDER_NUMBER  = 'GET_ORDER_NUMBER';
export const SEND_ORDER        = 'SEND_ORDER';
export const ADD_EMAIL_ADDRESS = 'ADD_EMAIL_ADDRESS';

//ROUTER
export const SET_PREVIOUS_ROUTE = 'GET_PREVIOUS_STATE';


